from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^$', 'portal.views.index'),
    (r'^image/(?P<picture_id>\d+)/$', 'portal.views.image'),
    (r'^autenticar/(?P<matricula>[^/]+)/(?P<rowguid>[^/]+)/$', 'portal.views.autenticar'),
    (r'^get_atualizacoes/(?P<matricula>[^/]+)/$', 'portal.views.get_atualizacoes'),
    (r'^importar_disciplinas/$', 'portal.views.importar_disciplinas'),
#    (r'^corrigir_disciplinas/$', 'portal.views.corrigir_disciplinas'),
    (r'^importar_alunos/$', 'portal.views.importar_alunos'),
    (r'^atualiza_informacao_periodo/(?P<periodo>[^/]+)/$', 'portal.views.atualiza_informacao_periodo'),
#    (r'^limpar/$', 'portal.views.limpar'),
    (r'^search/', 'portal.search.views.search'),
    (r'^i/', include('portal.institutions.urls')),
    (r'^c/', include('portal.courses.urls')),
    (r'^d/', include('portal.disciplines.urls')),
    (r'^g/', include('portal.groups.urls')),
    (r'^polls/', include('portal.polls.urls')),
    (r'^album/', include('portal.album.urls')),
    (r'^files/', include('portal.files.urls')),
    (r'^messages/', include('portal.messages.urls')),
    (r'^(?P<slug>[^/]+)/$', 'portal.institutions.views.detail'),
    (r'^(?P<inst_slug>[^/]+)/(?P<course_slug>[^/]+)/$', 'portal.courses.views.detail'),
    (r'^(?P<inst_slug>[^/]+)/(?P<course_slug>[^/]+)/(?P<disc_slug>[^/]+)/$', 'portal.disciplines.views.detail'),
)